services:
  postgres:
    image: postgres:17
    container_name: tanninsdb-postgres
    restart: always
    environment:
      POSTGRES_DB: tanninsdb
      POSTGRES_USER: tanninsdb
      POSTGRES_PASSWORD: tanninsdb
    ports:
      - "5432:5432"
    volumes:
      - tanninsdb_data:/var/lib/postgresql/data

volumes:
  tanninsdb_data: